/* German translation (de-DE) */
R.registerLocale('de-DE', 
{ 
  "title": 'Insulin Bolus Rechner',
  "subtitle": 'Blutzuckerspiegel und Mahlzeit eingeben',
  "glucoseTitle": 'Blutzuckerspiegel',
  "mealTitle": 'Menge der Mahlzeit',
  "breadUnits": '[BE] Broteinheiten',
  "carbUnits": '&nbsp;[g] Kohlenhydrate',
  "bolusTitle": 'Finaler Bolus',
  "sum": 'Mahl (%s) + Korr (%s)',
  "therapyTitle": 'Therapie Einstellung',
  "therapyName0": 'Morgens (%s-%s)',
  "therapyName1": 'Mittags (%s-%s)',
  "therapyName2": 'Abends (%s-%s)',
  "therapyName3": 'Nachts (%s-%s)',
  "therapyInfo": 'Ziel %s Korr %s Mahl %s',
  "glucoseAimTitle": 'Blutzucker Ziel',
  "correctionTitle": 'Korrektur Faktor',
  "mealFactorTitle": 'Mahlzeit Faktor',
  "appSetupTitle": 'Software Einstellungen',
  "carbsFactor": 'KH / Insulin Einheit',
  "appLanguage": 'Angezeigte Sprache',
  "donate": 'Spenden'
});
