/* English translation (en-GB) */
R.registerLocale('en-GB', 
{ 
  "title": 'Insulin Bolus Calculator',
  "subtitle": 'Enter glucose level and meal to be eaten',
  "glucoseTitle": 'Glucose Level',
  "mealTitle": 'Amount of Meal',
  "breadUnits": 'bread units',
  "carbUnits": 'gram carbs',
  "bolusTitle": 'Final Bolus',
  "sum": 'Meal (%s) + Corr (%s)',
  "therapyTitle": 'Therapy Setting',
  "therapyName0": 'Morning (%s-%s)',
  "therapyName1": 'Noontime (%s-%s)',
  "therapyName2": 'Evening (%s-%s)',
  "therapyName3": 'Night (%s-%s)',
  "therapyInfo": 'Aim %s Corr %s Meal %s',
  "glucoseAimTitle": 'Glucose Aim',
  "correctionTitle": 'Correction Factor',
  "mealFactorTitle": 'Meal Factor',
  "appSetupTitle": 'Application Setup',
  "carbsFactor": 'Carbs / Insulin Unit',
  "appLanguage": 'Displayed Language',
  "donate": 'Donate'
});
