/* Portuguese translation (en-GB) */
R.registerLocale('pt-PT',
{
  "title": 'Calculadora de Bolus de Insulina',
  "subtitle": 'Introduza o nível de glicose e a dimensão da refeição',
  "glucoseTitle": 'Glicémia',
  "mealTitle": 'Comida',
  "breadUnits": 'Porções de HC',
  "carbUnits": 'Gramas de HC',
  "bolusTitle": 'Bolus Final',
  "sum": 'Comida (%s) + Correção (%s)',
  "therapyTitle": 'Configurações terapêuticas',
  "therapyName0": 'Manhã (%s-%s)',
  "therapyName1": 'Meio-dia (%s-%s)',
  "therapyName2": 'Tarde (%s-%s)',
  "therapyName3": 'Noite (%s-%s)',
  "therapyInfo": 'Alvo %s Correção %s Comida %s',
  "glucoseAimTitle": 'Glicémia Alvo',
  "correctionTitle": 'Factor de Correção',
  "mealFactorTitle": 'Factor de Comida',
  "appSetupTitle": 'Configuração da Aplicação',
  "carbsFactor": 'HC / Un. de Insulina',
  "appLanguage": 'Idioma',
  "aboutLink": 'Sobre %s',
  "donate": 'Doar'
});
